name: "Main Deploy"

on:
    push:
        branches:
            - 'main'

permissions:
  id-token: write
  contents: read

jobs: 
    terraform:
        uses: ./.github/workflows/pipeline.yml
        with: 
            environment: prod